---
title: "Research"
output:
  distill::distill_article:           
    self_contained: true               
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Research Interests

- computational statistics
- finite mixture modeling
- model-based clustering
- data visualization

## Publications

- **Zhang,Y.,**, Melnykov,V., Chen,Y. (2025)  
  [Modeling and clustering of heterogeneous multivariate categorical sequences](https://www.sciencedirect.com/science/article/pii/S003132032500809X).   
  _Pattern Recognition_ 

- **Zhang,Y.,**, Melnykov,V., Zhu,X. (2025)  
  [Study on the overlap in matrix-variate data with applications in discriminant analysis](https://link.springer.com/article/10.1007/s13171-025-00406-9).   
  _Sankhya A_ 
  
  
- **Zhang,Y.,**, Sarkar,S., Chen,Y., Zhu,X. (2024)  
  [On regime changes in text data using hidden Markov model of contaminated vMF distribution](https://link.springer.com/article/10.1007/s10618-024-01051-w).   
  _Data Mining and Knowledge Discovery_ 

- **Zhang,Y.,**, Melnykov,V., Melnykov,I. (2023)  
  [On model-based clustering of directional data with heavy tails](https://link.springer.com/article/10.1007/s00357-023-09445-z).  
  _Journal of Classification_

- **Zhang,Y.,**, Melnykov,V., Melnykov,I. (2022)  
  [Semi-supervised clustering of time-dependent categorical sequences with application to discovering education-based life pattern](https://journals.sagepub.com/doi/10.1177/1471082X21989170).      
  _Statistical Modelling_

- **Zhang,Y.,**, Melnykov,V., Zhu,X. (2021)  
  [Model-based clustering of time-dependent categorical sequences with application to the analysis of major life event patterns](https://onlinelibrary.wiley.com/doi/abs/10.1002/sam.11502).  
  _Statistical Analysis and Data Mining_

- Chen,H., Zhu,C., **Zhang,Y.,** (2014)  
  [A note on exponential stability for impulsive neutral stochastic partial functional differential equations](https://www.sciencedirect.com/science/article/pii/S0096300313011156).  
  _Applied Mathematics and Computation_

## Under Review/Revision
- **Zhang,Y.,**,Zhu,X.,Tong,H., Melnykov,V.,   
  Model-based clustering of music sequences.  
  under review at *Pattern Recognition*

- **Zhang,Y.,**, Zhu,X.,  
  Study on the overlap of finite mixture modeling of categorical sequences.  
  Under review at *Advances in Data Analysis and Classification*

## In-progress
- Melnykov,Y., **Zhang,Y.,**, Zheng, R.,  
  Clustering analysis on the spatial-temporal and intensity patterns of tornado data in USA.   

- Chen, Y., **Zhang, Y.,**, Zhu, X., Tian, A.,  
  The effect of AI actions between leading and following corporations.   

- Joint work with Sarkar,S., Zhu,X.  
  On model-based clustering of multivariate categorical sequences with missing values. 
  
- Joint work with Su,H.  
  Analysis of Reddit depression community support through text-based methods.
  
- Joint work with Shields,B.  
  On model-based clustering of dynamic multivariate categorical sequences. 
  
- **Zhang, Y.,**
  Study on the overlap of high-dimensional finite mixture modeling of Gaussian distributions.
  
